In [1]:
import numpy as np
import pandas as pd

### Задание 1

In [2]:
a = np.arange(12, 24)

a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a1 = np.linspace(12, 23, 12)

a1

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

### Задание 2

In [4]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 3

In [9]:
a.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
a.reshape(-1, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 4

In [14]:
b = a.reshape(-1, 1)

In [15]:
b.shape

(12, 1)

In [16]:
b.ndim

2

**Ответ: нельзя, размерность массива = 2**

### Задание 5

In [17]:
r = np.random.randn(3, 4)

r

array([[ 0.89074492,  0.93372012,  1.18437358, -0.84018011],
       [-1.39777589,  0.84763447,  0.15579927,  1.66578022],
       [-0.45950189,  0.27276737,  0.01814677, -0.04238819]])

In [18]:
r_f = r.flatten()

r_f

array([ 0.89074492,  0.93372012,  1.18437358, -0.84018011, -1.39777589,
        0.84763447,  0.15579927,  1.66578022, -0.45950189,  0.27276737,
        0.01814677, -0.04238819])

In [19]:
print(r.size)
print(r_f.size)

12
12


### Задание 6

In [20]:
a = np.arange(20, 0, -2)

a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

In [21]:
b = np.arange(20, 0, -2).reshape(1, -1)

b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [22]:
print('Размерность массива а =', a.ndim)
print('Размерность массива b =', b.ndim)

Размерность массива а = 1
Размерность массива b = 2


### Задание 8

In [23]:
a = np.zeros((2, 2))

a

array([[0., 0.],
       [0., 0.]])

In [24]:
b = np.ones((3, 2))

b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
v = np.vstack((a, b))

v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
v.size

10

### Задание 9

In [27]:
a = np.arange(0, 12)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
A = a.reshape(4, 3)

A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
At = A.T

At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [30]:
B = np.dot(A, At)

B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [31]:
B.shape

(4, 4)

In [32]:
print('Определитель матрицы В =', np.linalg.det(B))
print('Ранг матрицы В =', np.linalg.matrix_rank(B))
print('Размер матрицы В:', np.shape(B))
print('Следовательно, матрица является вырожденной, у нее нет стандартной обратной матрицы')

Определитель матрицы В = 0.0
Ранг матрицы В = 2
Размер матрицы В: (4, 4)
Следовательно, матрица является вырожденной, у нее нет стандартной обратной матрицы


In [33]:
print('Псевдообратная матрица B+:\n\n', np.linalg.pinv(B))

Псевдообратная матрица B+:

 [[ 0.32333333  0.17444444  0.02555556 -0.12333333]
 [ 0.17444444  0.09425926  0.01407407 -0.06611111]
 [ 0.02555556  0.01407407  0.00259259 -0.00888889]
 [-0.12333333 -0.06611111 -0.00888889  0.04833333]]


### Задание 10

In [34]:
np.random.seed(42)

### Задание 11

In [35]:
c = np.random.randint(0, 16, 16)

c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Задание 12

In [36]:
C = c.reshape(4, 4)

C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [37]:
D = np.add(C * 10, B)

D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [38]:
np.linalg.det(D).round()

-28512000.0

In [39]:
np.linalg.matrix_rank(D)

4

In [40]:
D_inv = np.linalg.inv(D)

D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

### Задание 13

In [41]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0

D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [42]:
print('B:\n', B)
print('C:\n', C)
print('D_inv:\n', D_inv)

B:
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C:
 [[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
D_inv:
 [[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]


In [43]:
E = np.where(D_inv, B, C)

E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])